config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :articales do
    # one page
    collection do
      get :archived
    end
    #for each articale
    member do
      patch :report
    end
    member do
      patch :unarchive
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/articale.rb
class Articale < ApplicationRecord
  belongs_to:user
  mount_uploader :image, ImageUploader
  def published?
    published == true
  end
  def archived?
    report_number == 3
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many:articales


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :debug_user_state
  include Pundit
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  private
  
  def debug_user_state
    Rails.logger.info "Current user: #{current_user.inspect}"
    Rails.logger.info "User signed in?: #{user_signed_in?}"
    Rails.logger.info "Session: #{session.inspect}"
  end
end

app/controllers/articales_controller.rb
class ArticalesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_articale, only: [:show, :edit, :update, :destroy , :report, :unarchive]

  def index
    @articales = Articale.where(archived: [false, nil])
    authorize @articales
  end

  def show
  end

  def new
    @articale = Articale.new
    authorize @articale
  end

  def edit
    authorize @articale
  end

  def create
    @articale = Articale.new(articale_params)
    @articale.user = current_user
    authorize @articale

    if @articale.save
      redirect_to @articale, notice: 'Articale was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @articale

    if @articale.update(articale_params)
      redirect_to @articale, notice: 'Articale was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @articale
    @articale.destroy
    redirect_to articales_path, notice: 'Articale was successfully deleted.'
  end
  
  def report
    # @articale = Articale.find(params[:id])
    @articale.increment!(:report_number)
    if @articale.report_number == 3
      @articale.update(archived: true)
      redirect_to articales_path , notice: "This article has been archived after multiple reports."

    elsif @articale.report_number >= 6
      @articale.destroy #dont call path for destroy just destroy it
      redirect_to articales_path, alert: "The article has been removed due to repeated reports."
      else 
      redirect_to articales_path, notice: "Thank you for reporting this article."
    end
  end
  
  def archived
    @articales = current_user.articales.where(archived: true)
  end

  def unarchive
    authorize @articale
    @articale.update(archived: false)
    redirect_to articales_path, notice: "Article has been unarchived."
  end
  private

  def set_articale
    @articale = Articale.find(params[:id])
  end

  def articale_params
    params.require(:articale).permit(:title, :body, :published, :image,:report_number).merge(user_id: current_user.id)
  end #just parameter in premit are known in views
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articales_helper.rb
module ArticalesHelper
end

app/views/articales/_form.html.erb
<%= form_with(model: articale, local: true, html: { multipart: true }) do |form| %>
  <% if articale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articale.errors.count, "error") %> prohibited this articale from being saved:</h2>
      <ul>
        <% articale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>


  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <% if articale.image.present? %>
      <p>Current image:</p>
      <%= image_tag articale.image.url, width: 100 %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articales/archived.html.erb
<h1>Archived Articles</h1>
<div class="container">
    <% @articales.each do |articale| %>
        <div class="article-card">
            <h2><%= articale.title %></h2>
            <p><%= truncate(articale.body, length: 100) %></p>

            <%= button_to  unarchive_articale_path(articale), method: :patch do class: "archive-link"%>
                <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-archive-off"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 4h11a2 2 0 1 1 0 4h-7m-4 0h-3a2 2 0 0 1 -.826 -3.822" /><path d="M5 8v10a2 2 0 0 0 2 2h10a2 2 0 0 0 1.824 -1.18m.176 -3.82v-7" />
                <path d="M10 12h2" />
                <path d="M3 3l18 18" />
                </svg>
            <%end%>
        </div>
    <% end %>

</div>

<%= link_to "Back to Home", articales_path %>

app/views/articales/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form', articale: @articale %>

<%= link_to 'Back', articale_path(@articale) %>

app/views/articales/index.html.erb
<div class="container">
    <h1>Articles</h1>
<%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>

    <%= link_to new_articale_path, class: "new-article-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="#ffffff" stroke-width="2" viewBox="0 0 24 24" stroke-linecap="round" stroke-linejoin="round">
        <line x1="12" y1="5" x2="12" y2="19" />
        <line x1="5" y1="12" x2="19" y2="12" />
    </svg>
    <% end %>
    <%= link_to archived_articales_path, class: "archive-link" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-archive" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="#ff6a00" fill="white" stroke-linecap="round" stroke-linejoin="round">
        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
        <rect x="3" y="4" width="18" height="4" rx="2" />
        <path d="M5 8v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1 -1v-12" />
        <line x1="10" y1="12" x2="14" y2="12" />
    </svg>
    <% end %>



    <% @articales.each do |articale| %>
        <% if articale.published %>
            <div class= "article-card">
                <h2><%= link_to articale.title, articale_path(articale) %></h2>
                <p><%= truncate(articale.body, length: 100) %></p>
                <% if articale.image.present? %>
                <img src="<%= articale.image.url %>" class="article-image" />            
                <% end %>
            </div>
        <% end %>
    <% end %>


</div>

app/views/articales/new.html.erb
<h1>New Article</h1>

<%= render 'form', articale: @articale %>
<%= link_to 'Back', articales_path %>

app/views/articales/show.html.erb
<div class="container">

  <div class= "article-card">

    <% if @articale.user == current_user %>
      <%= link_to edit_articale_path(@articale),class:"archive-link" do %> 
        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-pencil"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 20h4l10.5 -10.5a2.828 2.828 0 1 0 -4 -4l-10.5 10.5v4" /><path d="M13.5 6.5l4 4" /></svg>      <%end%>
      <%= button_to @articale, method: :delete,
      form: { class: "inline-form" },
      class: "btn-orange",
      data: { turbo_confirm: "Are you sure?" } do %>
        <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="currentColor"  class="icon icon-tabler icons-tabler-filled icon-tabler-trash"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M20 6a1 1 0 0 1 .117 1.993l-.117 .007h-.081l-.919 11a3 3 0 0 1 -2.824 2.995l-.176 .005h-8c-1.598 0 -2.904 -1.249 -2.992 -2.75l-.005 -.167l-.923 -11.083h-.08a1 1 0 0 1 -.117 -1.993l.117 -.007h16z" /><path d="M14 2a2 2 0 0 1 2 2a1 1 0 0 1 -1.993 .117l-.007 -.117h-4l-.007 .117a1 1 0 0 1 -1.993 -.117a2 2 0 0 1 1.85 -1.995l.15 -.005h4z" /></svg>
      <% end %>
    <% end %>
  <%if @articale.user != current_user%>
    <%= button_to  report_articale_path(@articale), method: :patch,
    form: { class: "inline-form" },class: "btn-report", 
    data: { turbo_confirm: "Are you sure you want to report this article?" } do%>
    <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="red"  class="icon icon-tabler icons-tabler-filled icon-tabler-flag-2"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19 4a1 1 0 0 1 .993 .883l.007 .117v9a1 1 0 0 1 -.883 .993l-.117 .007h-13v6a1 1 0 0 1 -.883 .993l-.117 .007a1 1 0 0 1 -.993 -.883l-.007 -.117v-16a1 1 0 0 1 .883 -.993l.117 -.007h14z" /></svg>
    <%end%>
  <%end%>
 
  <h1><%= @articale.title %></h1>

  <p><%= @articale.body %></p>

  <% if @articale.image.present? %>
      <img src="<%= @articale.image.url %>" class="article-image" />            
  <% end %>


  <p><strong>Published:</strong> <%= @articale.published ? "Yes" : "No" %></p>

 
</div>
  <%= link_to  articales_path do %>
  <svg  xmlns="http://www.w3.org/2000/svg"  width="24"  height="24"  viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round"  class="icon icon-tabler icons-tabler-outline icon-tabler-arrow-left"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 12l14 0" /><path d="M5 12l6 6" /><path d="M5 12l6 -6" /></svg>
  <%end%>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>